info:
  foo: bar
services:
  user:
    name: user
    database:
      name: mysql
      url: jdbc:mysql://localhost:3306/user-db?createDatabaseIfNotExist=true
      username: root
      password: FormosVN@123
